In [1]:
import numpy as np

In [2]:
def get_cosine_similarity(array_1: np.ndarray[int, int], array_2: np.ndarray[int, int]) -> float:
    """Функция подсчета косинусного подобия."""
    return np.dot(array_1, array_2)/ (np.linalg.norm(array_1) * np.linalg.norm(array_2))

In [3]:
input_data = np.array(
    [
        [5, 4, 5, 3, 5],
        [5, 5, 5, 3, 5],
        [5, 4, 4, 2, 5],
        [5, 3, 5, 0, 3],
        [5, 0, 5, 0, 0],
        [4, 5, 5, 3, 1],
    ],
    dtype=int,
)
input_data

array([[5, 4, 5, 3, 5],
       [5, 5, 5, 3, 5],
       [5, 4, 4, 2, 5],
       [5, 3, 5, 0, 3],
       [5, 0, 5, 0, 0],
       [4, 5, 5, 3, 1]])

In [4]:
products_count, users_count = input_data.shape
products_count, users_count

(6, 5)

# Расчет близких продуктов

In [5]:
products_similarity_matrix: np.ndarray[(int, int), float] = np.full(
    (products_count, products_count),
    -2,
    dtype=float,
)

for i in range(products_count):
    for j in range(i + 1, products_count):
        similarity_value = get_cosine_similarity(input_data[i], input_data[j])
        products_similarity_matrix[i, j] = similarity_value

products_similarity_matrix

array([[-2.        ,  0.99613934,  0.99206151,  0.93376216,  0.70710678,
         0.90619215],
       [-2.        , -2.        ,  0.99153662,  0.92922799,  0.67728546,
         0.92290976],
       [-2.        , -2.        , -2.        ,  0.94151841,  0.68624357,
         0.87821799],
       [-2.        , -2.        , -2.        , -2.        ,  0.85749293,
         0.87635344],
       [-2.        , -2.        , -2.        , -2.        , -2.        ,
         0.7299964 ],
       [-2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        ]])

In [6]:
products_flatten_max_index = np.argmax(products_similarity_matrix)
products_indices = divmod(int(products_flatten_max_index), products_count)
print('Лучшая пара продуктов:', products_indices)

Лучшая пара продуктов: (0, 1)


# Расчет близких пользователей

In [7]:
users_similarity_matrix: np.ndarray[(int, int), float] = np.full(
    (users_count, users_count),
    -2,
    dtype=float,
)

users_input_data = input_data.transpose()

for i in range(users_count):
    for j in range(i + 1, users_count):
        similarity_value = get_cosine_similarity(users_input_data[i], users_input_data[j])
        users_similarity_matrix[i, j] = similarity_value

users_similarity_matrix

array([[-2.        ,  0.88281509,  0.9929078 ,  0.78652574,  0.85863549],
       [-2.        , -2.        ,  0.89164324,  0.94138757,  0.89824939],
       [-2.        , -2.        , -2.        ,  0.80165124,  0.82209781],
       [-2.        , -2.        , -2.        , -2.        ,  0.83768   ],
       [-2.        , -2.        , -2.        , -2.        , -2.        ]])

In [8]:
users_flatten_max_index = np.argmax(users_similarity_matrix)
users_indices = divmod(int(users_flatten_max_index), users_count)
print('Лучшая пара пользователей:', users_indices)

Лучшая пара пользователей: (0, 2)
