In [1]:
from IPython.display import display
import numpy as np


In [2]:
# Входные данные
input_data = np.array(
    [
        [1, 0, 0, 0, 2, 0],
        [0, 0, 3, 4, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 8, 0, 5],
        [0, 0, 0, 0, 0, 0],
        [0, 7, 1, 0, 0, 6],
    ],
    dtype=int,
)
input_data


array([[1, 0, 0, 0, 2, 0],
       [0, 0, 3, 4, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 8, 0, 5],
       [0, 0, 0, 0, 0, 0],
       [0, 7, 1, 0, 0, 6]])

# Получение индексов ненулевых элементов

In [3]:
non_zeros_rows, non_zeros_cols = input_data.nonzero()
non_zeros_rows, non_zeros_cols

(array([0, 0, 1, 1, 3, 3, 5, 5, 5]), array([0, 4, 2, 3, 3, 5, 1, 2, 5]))

In [4]:
non_zeros_values = np.array([
    input_data[i, j]
    for i, j in zip(non_zeros_rows.tolist(), non_zeros_cols.tolist())
])
non_zeros_values

array([1, 2, 3, 4, 8, 5, 7, 1, 6])

In [5]:
print('Rows:'); display(non_zeros_rows)
print('Columns:'); display(non_zeros_cols)
print('Values:'); display(non_zeros_values)

Rows:


array([0, 0, 1, 1, 3, 3, 5, 5, 5])

Columns:


array([0, 4, 2, 3, 3, 5, 1, 2, 5])

Values:


array([1, 2, 3, 4, 8, 5, 7, 1, 6])

# Формирование массива Row Index

In [6]:
from collections import Counter

In [7]:
rows_indices_conter = Counter(list(non_zeros_rows))
indices_counts_map = dict(rows_indices_conter)
sorted_indices = sorted(indices_counts_map)
indices_counts_map, sorted_indices

({np.int64(0): 2, np.int64(1): 2, np.int64(3): 2, np.int64(5): 3},
 [np.int64(0), np.int64(1), np.int64(3), np.int64(5)])

In [8]:
non_zeros_rows_indices = [0]

for i in range(sorted_indices[-1]):
    if count := indices_counts_map.get(i):
        non_zeros_rows_indices.append(non_zeros_rows_indices[-1] + count)
    else:
        non_zeros_rows_indices.append(non_zeros_rows_indices[-1])

non_zeros_rows_indices

[0, 2, 4, 4, 6, 6]

In [9]:
print('Rows Indices:'); display(np.array(non_zeros_rows_indices))
print('Columns:'); display(non_zeros_cols)
print('Values:'); display(non_zeros_values)

Rows Indices:


array([0, 2, 4, 4, 6, 6])

Columns:


array([0, 4, 2, 3, 3, 5, 1, 2, 5])

Values:


array([1, 2, 3, 4, 8, 5, 7, 1, 6])

# Формирование матриц Value и Column

In [10]:
total_rows_count = input_data.shape[0]
((_, most_rich_row_count),) = rows_indices_conter.most_common(1)

matrix_shape = (total_rows_count, most_rich_row_count)
matrix_shape

(6, 3)

In [11]:
matrix_of_values = np.zeros(matrix_shape, dtype=int)
matrix_of_columns = np.zeros(matrix_shape, dtype=int)
matrix_of_values, matrix_of_columns

(array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [12]:
current_index = 0

for row, row_count in indices_counts_map.items():
    for matrix_col in range(row_count):
        matrix_of_values[row, matrix_col] = non_zeros_values[current_index]
        matrix_of_columns[row, matrix_col] = non_zeros_cols[current_index]
        current_index += 1


In [13]:
print('Columns:'); display(matrix_of_columns)
print('Values:'); display(matrix_of_values)

Columns:


array([[0, 4, 0],
       [2, 3, 0],
       [0, 0, 0],
       [3, 5, 0],
       [0, 0, 0],
       [1, 2, 5]])

Values:


array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0],
       [8, 5, 0],
       [0, 0, 0],
       [7, 1, 6]])

# Исключение:

- Товаров с нулевым рейтингом;
- Товаров с низким рейтингом (<4);
- Неактивных пользователей.

In [14]:
# Входные данные
input_data = np.array(
    [
        [5, 4, 5, 0, 5],
        [5, 5, 5, 0, 5],
        [5, 4, 4, 0, 5],
        [4, 3, 4, 0, 3],
        [0, 0, 0, 0, 0],
        [4, 5, 5, 0, 1],
    ],
    dtype=int,
)
input_data

array([[5, 4, 5, 0, 5],
       [5, 5, 5, 0, 5],
       [5, 4, 4, 0, 5],
       [4, 3, 4, 0, 3],
       [0, 0, 0, 0, 0],
       [4, 5, 5, 0, 1]])

In [15]:
# Исключение товаров с нулевым рейтингом.
sparsed_matrix = input_data[~np.all(input_data == 0, axis=1)]
sparsed_matrix

array([[5, 4, 5, 0, 5],
       [5, 5, 5, 0, 5],
       [5, 4, 4, 0, 5],
       [4, 3, 4, 0, 3],
       [4, 5, 5, 0, 1]])

In [16]:
# Исключение товаров с низким рейтингом.
sparsed_matrix = sparsed_matrix[:, ~np.all(sparsed_matrix == 0, axis=0)]
sparsed_matrix

array([[5, 4, 5, 5],
       [5, 5, 5, 5],
       [5, 4, 4, 5],
       [4, 3, 4, 3],
       [4, 5, 5, 1]])

In [17]:
sparsed_matrix = sparsed_matrix[np.mean(sparsed_matrix, axis=1) >= 4]
sparsed_matrix

array([[5, 4, 5, 5],
       [5, 5, 5, 5],
       [5, 4, 4, 5]])

In [18]:
print('Sparsed matrix:'); display(sparsed_matrix)

Sparsed matrix:


array([[5, 4, 5, 5],
       [5, 5, 5, 5],
       [5, 4, 4, 5]])